var gfc_co=osapi,gfc_do="ceil";gfc_1[gfc_].Pi=gfc_xd(20,function(a,b,c){return a?c<b?[]:a[gfc_Cc](gfc_d.min(b,a[gfc_C]),gfc_d.min(c,a[gfc_C])):[]});gfc_1[gfc_].share=gfc_xd(18,function(){gfc_yn();return!1});gfc_1[gfc_].Lf=gfc_xd(16,function(){return this.Qb.pop()});gfc_1[gfc_].pj=gfc_xd(15,function(){var a=this.Gd;a.valid?(this.f=this.Ug(this.Gd),this.pi(a[gfc_dd])):(this.Gd=null,this.render(a.actions,a[gfc_dd],a.params));this.Rg()});
gfc_oa(gfc_Df[gfc_],gfc_xd(3,function(){this.x=gfc_d[gfc_do](this.x);this.y=gfc_d[gfc_do](this.y);return this}));gfc_oa(gfc_Ff[gfc_],gfc_xd(2,function(){gfc_ma(this,gfc_d[gfc_do](this[gfc_i]));gfc_Ia(this,gfc_d[gfc_do](this[gfc_v]));return this}));gfc_oa(gfc_vh[gfc_],gfc_xd(1,function(){this.top=gfc_d[gfc_do](this.top);gfc_Ja(this,gfc_d[gfc_do](this[gfc_sc]));gfc_Ea(this,gfc_d[gfc_do](this[gfc_dc]));gfc_Qa(this,gfc_d[gfc_do](this[gfc_A]));return this}));
gfc_oa(gfc_wh[gfc_],gfc_xd(0,function(){gfc_Qa(this,gfc_d[gfc_do](this[gfc_A]));this.top=gfc_d[gfc_do](this.top);gfc_ma(this,gfc_d[gfc_do](this[gfc_i]));gfc_Ia(this,gfc_d[gfc_do](this[gfc_v]));return this}));
var gfc_eo=function(a){return a=gfc_b[gfc_jd]+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ra();this.cs();var d=new gfc_Q;d.set("members",{action:this.kv,callback:this.ku});d.set("member-page",{action:this.jv,callback:this.ju});d.set("blocked-member-page",{action:this.dv,callback:this.fu});d.set("profile-friends-page",{action:this.pv,callback:this.ou});d.set("sitesData",{action:this.xv,callback:this.su});d.set("viewerFriends",{action:this.Cv,callback:this.uu});d.set("profileData",
{action:this.ov,callback:this.nu});d.set("blockUser",{action:this.cv,callback:this.eu});d.set("unblockUser",{action:this.Av,callback:this.tu});d.set("profileFriends",{action:this.qv,callback:this.pu});d.set("activityData",{action:this.Uf,callback:this.rd});d.set("sendFriendRequest",{action:this.wv,callback:this.ru});d.set("sendFriendRequestResponse",{action:this.gv,callback:this.Nm});d.set("deleteActivity",{action:this.Vf,callback:this.rd});d.set("requestAndProcessViewerNumWaitingMessages",{action:this.Dv,
callback:this.wu});d.set("requestPromo",{action:this.rv,callback:this.qu});this.vb=null;this.ny=new gfc_Gn("fc-members-options-menu",gfc_K(this.It,this),gfc_K(this.Ht,this),gfc_K(this.Jt,this),0,gfc_b[gfc_jd],this.h("ENDCAP_LINK_COLOR")||"0000cc",this.h("CONTENT_TEXT_COLOR")||"000000");this.Pw=!1;this.Ka=10;this.Ff=15;this.Tn=10;var e=gfc_Zh(gfc_Gh()),f=gfc_fo;this.dc=3;this.Bc=8;this.qn=null;this.va=this.Bc*this.dc;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;this.isMessagingEnabled=a;this.isPromosEnabled=
b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.Yb=new gfc_Cn;this.ji()&&(a=(a=this.h(f.FACE_SIZE))?gfc_ga(a):32,a+=6,this.dc=gfc_d[gfc_7a]((e[gfc_i]-10)/a),e=340,e=this.h(f.HEIGHT),(f=this.h(f.NUMBER_ROWS))?(this.Bc=gfc_ga(f),e=this.Bc*a,this.qn=e+27):e&&(e=gfc_ga(e)-96,this.Bc=gfc_d.max(2,gfc_d[gfc_7a](e/a)),this.qn=this.Bc*a+27),this.va=this.Bc*this.dc);gfc_1[gfc_G](this,d)};gfc_7.inherits(gfc_1);
gfc_Ca(gfc_7[gfc_],function(){gfc_7.l[gfc_u][gfc_G](this);gfc_$m("start");var a=gfc_a[gfc_s][gfc_Nc](),b=gfc_ca();(a=b.profileId||a.profileId)?(b={},b[gfc_e[gfc_y][gfc_r].ID]=a,a=new gfc_e[gfc_y](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_w]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Ub()&&a[gfc_w]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].g={};
gfc_7[gfc_].Ra=function(){this.g.MSG_SITE_MEMBERS="Members";this.g.MSG_BE_THE_FIRST="Be the first!";this.g.MSG_NO_SITE_MEMBERS="There are no members yet.";this.g.MSG_ALL_SITE_MEMBERS="All Members";this.g.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.g.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.g.MSG_YOUR_FRIENDS="Your Friends";this.g.MSG_ALL_YOUR_FRIENDS="All Your Friends";this.g.MSG_JFJ="Join and connect with others!";this.g.MSG_MANAGE="Manage members";this.g.MSG_SETTINGS=
"Settings";this.g.MSG_OPTIONS="Options";this.g.MSG_MEMBERS_SHARE="Share this page";this.g.MSG_BACK="Back";this.g.MSG_BACK_TO_TOP="Home";this.g.MSG_VIEW_MY_PROFILE="View my profile";this.g.MSG_ABOUT_ME="About me";this.g.MSG_MORE="More \u00bb";this.g.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.g.MSG_SHOW_ALL="\u00ab Show all members";this.g.MSG_LINK_IN_NETWORKS="Link in your social networks";this.g.MSG_ACTIVITIES="Activities";this.g.MSG_ALL_ACTIVITIES="More activities";this.g.MSG_DELETE_THIS=
"Delete";this.g.MSG_SITES="Sites I've joined";this.g.MSG_ALL_SITES="More sites I've joined";this.g.MSG_LINKS="Links";this.g.MSG_ALL_LINKS="More links";this.g.MSG_NO_ACTIVITIES="No activities to show";this.g.MSG_ADD_AS_FRIEND="Add as friend";this.g.MSG_SEND_MESSAGE="Send a message";this.g.MSG_BLOCK_USER="Block this user";this.g.MSG_UNBLOCK_USER="Unblock this user";this.g.MSG_USER_IS_ADMIN="Administrator";this.g.MSG_JOIN="Join this site";this.g.MSG_OR="or";this.g.MSG_SIGN_IN="Sign in";this.g.MSG_SIGN_OUT=
"Sign out";this.g.MSG_PREVIOUS="\u00ab Previous";this.g.MSG_NEXT="Next \u00bb";this.g.MSG_NEWER="\u00ab Newer";this.g.MSG_OLDER="Older \u00bb";this.g.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.g.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.g.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";this.g.MSG_HELP_BLOCKMEMBER="Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";
this.g.MSG_INVITATION="Invitation:";this.g.MSG_SEND="Send";this.g.MSG_BLOCK="Block";this.g.MSG_IGNORE="Ignore";this.g.MSG_CANCEL="Cancel";this.g.MSG_SITE_SETTINGS="Site settings";this.g.MSG_ABOUT_FC="About Friend Connect";this.g.MSG_ALREADY_MEMBER="Already a member?";this.g.MSG_EDIT_PROFILE="Edit profile"};gfc_7[gfc_].xa={};
gfc_7[gfc_].cs=function(){this.xa.MSG_SITE_MEMBERS="Followers";this.xa.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.xa.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.xa.MSG_SHOW_ALL="\u00ab Show all followers";this.xa.MSG_ALL_SITE_MEMBERS="All Followers";this.xa.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.xa.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";this.xa.MSG_LIKE_THIS_SITE="Like this blog?";this.xa.MSG_JOIN="Follow";this.xa.MSG_BACK_TO_TOP="Members";
this.xa.MSG_JFJ="Follow and connect with your friends!";this.xa.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.xa.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_7[gfc_].Y=function(a,b){var c=!0;if(b[gfc_o]&&b[gfc_o].person){var d={},e=b[gfc_o].person[gfc_0b]()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b[gfc_o].person[gfc_0b]()+" to be your friend");d.MSG_IS_INVITED=e;e=b[gfc_o].person[gfc_0b]()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b[gfc_o].person[gfc_0b]()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.j(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_0b]()&&(d=gfc_c[gfc_i]?gfc_c[gfc_i]:gfc_c[gfc_D][gfc_3c]+2,c=(d-135)/
8,d=(d-175)/8,c="View "+(gfc__m(b.invitedBy[gfc_0b](),c)+"'s profile"),d=gfc__m(b.invitedBy[gfc_0b](),d)+" invited you to this site",this.j(a,"MSG_VIEW_INVITER_PROFILE",c),this.j(a,"MSG_INVITED_YOU",d),this.Pw=!0,c=!1);d=this.numWaitingMessages+" messages waiting for you.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.j(a,"showWaitingMessages",!0),this.isMessagingEnabled&&(this.j(a,"MSG_NUM_WAITING_MESSAGES",d),this.j(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","View messages")));b.friendRequests&&
(0<b.friendRequests[gfc_Nb]()&&(c=!1),d=1==b.friendRequests[gfc_Nb]()?"New friend request \u00bb":"New friend requests ("+(b.friendRequests[gfc_Nb]()+") \u00bb"),this.j(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.vb){if(this.Ll(this.vb.themeId))for(f in this.xa)this.j(a,f,this.xa[f]);this.vb.signInPrompt&&this.j(a,"MSG_JOIN",this.vb.signInPrompt);this.vb.signOutPrompt&&this.j(a,"MSG_SIGN_OUT",this.vb.signOutPrompt)}this.j(a,"isViewerAdmin",b.isViewerAdmin);this.j(a,"isMessagingEnabled",this.isMessagingEnabled);
this.j(a,"acceptMessages",this.Ao);this.j(a,"isViewingSelf",b.viewer&&b[gfc_o]&&b[gfc_o].person&&b.viewer[gfc_F]()==b[gfc_o].person[gfc_F]());d=!1;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=!0;this.j(a,"communityHasProfile",d);this.j(a,"promoHtml",c?this.promoHtml:null);this.j(a,"insertHtml",function(a,b){gfc_Ma(a,b)})};gfc_7[gfc_].Ll=function(a){return"blogger"==a};gfc_7[gfc_].ih=function(a,b,c,d){gfc_wn({id:a,text:b,version:this.Ll(this.vb.themeId)?1:null,style:c},d)};
gfc_7[gfc_].fa=function(a){function b(b,c){d.j(a,b,gfc_K(c,d))}this.j(a,"facesPerRow",this.dc);for(var c in this.g)this.j(a,c,this.g[c]);var d=this;b("getThumbnail",this.Hc);b("map",this.map);b("elide",gfc__m);b("safeSlice",this.Pi);b("showAllActivities",this.Aw);b("transformActivity",this.qc);b("nextActivities",this.ht);b("previousActivities",this.St);b("showAllLinks",this.Cw);b("transformLink",this.ox);b("nextLinks",this.lt);b("previousLinks",this.Ut);b("showAllSites",this.Fw);b("transformSite",
this.px);b("nextSites",this.st);b("previousSites",this.$t);b("showAllMembers",this.Dw);b("showBlockedMembers",this.Hw);b("showUnblockedMembers",this.Yw);b("nextMembers",this.mt);b("nextBlockedMembers",this.it);b("previousMembers",this.Vt);b("previousBlockedMembers",this.Tt);b("showAllProfileFriends",this.Ew);b("nextProfileFriends",this.rt);b("previousProfileFriends",this.Zt);b("showAllViewerFriends",this.Gw);b("nextViewerFriends",this.tt);b("previousViewerFriends",this.au);b("isHome",this.gi);b("goBack",
this.Gh);b("goBackToHome",this.Rw);b("editSettings",this.Nb);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.qo);b("blockUser",this.Rj);b("unblockUser",this.tx);b("goToInviteFriend",this.fr);b("sendMessageDialog",this.Xv);b("goToBlockMember",this.er);b("goToEditProfile",this.Nb);b("goToViewerProfile",this.gr);b("sendInvite",this.Wv);b("blockMember",this.Uo);b("acceptFriendRequest",this.zo);b("ignoreFriendRequest",this.bs);b("viewFriendRequests",this.Cx);b("acceptAllFriendRequests",
this.yo);b("numPreviewFriends",this.Lq);b("numPreviewMembers",this.Mq);b("showInvitedBy",this.Sq)};
gfc_7[gfc_].el=function(a){a=gfc_d.max(1,a?this.Bc-1:this.Bc);var b=this.f[gfc_k].members?this.f[gfc_k].members[gfc_Nb]():0,c=this.f[gfc_k].friends?this.f[gfc_k].friends[gfc_Nb]():0,b=gfc_d[gfc_do](b/this.dc),c=gfc_d[gfc_do](c/this.dc);b>gfc_d[gfc_do](a/2)?c>gfc_d[gfc_7a](a/2)?(b=gfc_d[gfc_do](a/2),c=gfc_d[gfc_7a](a/2)):b=gfc_d.max(0,a-c):c>gfc_d[gfc_7a](a/2)&&(c=gfc_d.max(0,a-b));b*=this.dc;c*=this.dc;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Mq=function(a){return this.el(a).numMembers};
gfc_7[gfc_].Lq=function(a){return this.el(a).numFriends};gfc_7[gfc_].jv=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_E][gfc_Sc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_u];d[e.MAX]=b.pageSize?b.pageSize:this.va;var f=[gfc_e[gfc_y][gfc_r].ID,gfc_e[gfc_y][gfc_r][gfc_2a],gfc_e[gfc_y][gfc_r][gfc_Bb]];d[e[gfc_ic]]=f;d[gfc_e[gfc_E].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_5c];c.add(c[gfc_8b](gfc_ze(),d),"ownerFriends");c[gfc_n](a)};
gfc_7[gfc_].ju=function(a){this.f[gfc_k].members=a.get("ownerFriends")[gfc_l]()};gfc_7[gfc_].dv=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_E][gfc_Sc];d[e.FIRST]=b[gfc_u];d[e.MAX]=b.pageSize?b.pageSize:this.va;d[gfc_e[gfc_E].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_5c];e={};e[gfc_e[gfc_Hb][gfc_r][gfc__b]]=gfc_e[gfc_Hb].PersonId.OWNER;e[gfc_e[gfc_Hb][gfc_r][gfc_Ub]]="BLOCKED";e[gfc_e[gfc_Hb][gfc_r][gfc_vc]]=1;e=gfc_e[gfc_rc](e);c.add(c[gfc_8b](e,d),"blockedMembers");c[gfc_n](a)};
gfc_7[gfc_].fu=function(a){this.f[gfc_k].blockedMembers=a.get("blockedMembers")[gfc_l]()};gfc_7[gfc_].pv=function(a,b){var c=gfc_e[gfc_H](),d=b&&b.person&&b.person[gfc_F]()||this.H[gfc_o].person[gfc_F](),e={},f=gfc_e[gfc_E][gfc_Sc];e[f.FIRST]=b[gfc_u];e[f.MAX]=b.pageSize?b.pageSize:this.va;d=this.qm(d);e[gfc_e[gfc_E].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_5c];c.add(c[gfc_8b](d,e),"profileFriends");c[gfc_n](a)};
gfc_7[gfc_].qm=function(a){var b={};b[gfc_e[gfc_Hb][gfc_r][gfc__b]]=a;b[gfc_e[gfc_Hb][gfc_r][gfc_Ub]]="FRIENDS";b[gfc_e[gfc_Hb][gfc_r][gfc_vc]]=1;return gfc_e[gfc_rc](b)};gfc_7[gfc_].ou=function(a){this.f[gfc_k][gfc_o].friends=a.get("profileFriends")[gfc_l]()};gfc_7[gfc_].Jj=function(a){for(var b=gfc_e[gfc_k].getDataContext(),c=0;c<a[gfc_C];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_7[gfc_].kv=function(a){var b=this.va,c=!b||24==b;c&&gfc_e[gfc_k]&&this.Jj(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(c=gfc_co.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_co.people.get(b)),c.add("viewer",gfc_co.people.getViewer()),c.add("siteSettings",gfc_co.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_co.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_ca().psinvite)&&c.add("invitedBy",gfc_co.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].ku=function(a,b){this.f[gfc_k].members=gfc_re(a.ownerFriends,gfc_me);this.f[gfc_k].viewer=gfc_me(a.viewer);this.Nm(a,b,!0);this.vb=a[gfc_Tc];var c=gfc_ca();!c.psinvite||null!=this.f[gfc_k].viewer&&""!=this.f[gfc_k].viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.f[gfc_k].invitedBy=new gfc_e[gfc_y](a.invitedBy))};
gfc_7[gfc_].Cv=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_u]||0==b[gfc_u],e=!c||20==c;d&&e&&gfc_e[gfc_k]&&this.Jj(["friends","isViewerAdmin"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(d=gfc_co.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_u]&&(c.startIndex=b[gfc_u]),d.add("friends",gfc_co.people.get(c)),d.add("isViewerAdmin",gfc_co.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].uu=function(a){var b=a.friends;b&&!b[gfc_tc]&&(this.f[gfc_k].friends=gfc_re(b,gfc_me));this.un(a)};gfc_7[gfc_].Dv=function(a){var b=gfc_e[gfc_H]();b.add(gfc_pe("VIEWER"),"numWaitingMessages");b[gfc_n](a)};gfc_7[gfc_].wu=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_l]().numberOfWaitingMessages};
gfc_7[gfc_].rv=function(a){this.log("requesting promo");var b=new gfc_a.Prefs,b=b.getLang()+(b.getCountry()?"_"+b.getCountry():""),c=gfc_e[gfc_H]();c.add(gfc_ee("GetPromo",{hl:b}),"promo");c[gfc_n](a)};gfc_7[gfc_].qu=function(a){this.log("processing promo");(a=a.get("promo")[gfc_l]())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_7[gfc_].Ho=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_9f("div","fc-promo-main",gfc_O("peg")),b=0;b<a[gfc_C];b++)gfc_1h(a[b],!1);this.ga();this.log("Dismissing promo "+this.promoCode);a=gfc_e[gfc_H]();a.add(gfc_ee("DismissPromo",{promoCode:this.promoCode}));a[gfc_n](gfc_K(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_9f("a","fc-promo-dismiss-link",gfc_O("peg")),c=0;c<b[gfc_C];c++){var d=b[c],e="click";gfc_5i(d,e);gfc_Wi(d,e,gfc_K(a,
this))}};gfc_7[gfc_].un=function(a){var b=a.isViewerAdmin;b&&!b[gfc_tc]?this.f[gfc_k].isViewerAdmin=b.list[gfc_C]:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Gc]()&&(this.f[gfc_k].isViewerAdmin=a[gfc_l]()[gfc_Nb]())};gfc_7[gfc_].yo=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_r].INVITER)[gfc_F](),action:"ACCEPT"};b[gfc_w](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Pg,this),{friendRequestResponses:b})};
gfc_7[gfc_].Rw=function(){this.pa();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].zo=function(a){a={user:a[gfc_F](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Pg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Cx=function(){this.pa();this.L("friend-requests")};gfc_7[gfc_].qo=function(a){this.Ub()?(this.pa(),this.Ex(a)):gfc_be(a[gfc_F]())};
gfc_7[gfc_].Ex=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].xv=function(a,b){var c=gfc_e[gfc_H](),d=gfc_e[gfc_E][gfc_Sc],e={};e[d.FIRST]=b&&b[gfc_u]?b[gfc_u]:0;var f=this.f[gfc_k][gfc_o].person[gfc_F]();e[d.MAX]=this.Tn;c.add(gfc_we(gfc_e[gfc_rc]({userId:f}),e),"profileSites");c[gfc_n](a)};gfc_7[gfc_].su=function(a){this.f[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]()};
gfc_7[gfc_].ov=function(a,b){this.f[gfc_k].profile={};b=b||{};var c=b.person,d={},c=c[gfc_F](),e=gfc_e[gfc_H](),f=[gfc_e[gfc_y][gfc_r].ID,gfc_e[gfc_y][gfc_r][gfc_2a],gfc_e[gfc_y][gfc_r][gfc_Bb],gfc_e[gfc_y][gfc_r].ABOUT_ME,gfc_e[gfc_y][gfc_r].URLS,"profileExtensions"],g=gfc_e[gfc_E][gfc_Sc];d[g[gfc_ic]]=f;d[gfc_e[gfc_E].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_5c];e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_ue("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.vb||e.add(gfc_oe(),"siteSettings");e.add(gfc_ue(c,"ADMINS"),"isAdmin");e.add(gfc_ue(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_pe(c),"canMessage");e[gfc_n](a)};
gfc_7[gfc_].Uf=function(a,b){var c=b.person[gfc_F](),d=gfc_e[gfc_rc]({userId:c}),e=gfc_e[gfc_H]();(this.f[gfc_k].viewer&&c!=this.f[gfc_k].viewer[gfc_F]()||this.Ub())&&e.add(gfc_te(b.person[gfc_F](),"VIEWER"),"isProfileFriend");e.add(e[gfc_9c](d,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].rd=function(a,b){null!=a.get("activities")[gfc_l]()&&(this.f[gfc_k][gfc_o].activities=a.get("activities")[gfc_l]());var c=a.get("isProfileFriend");c&&b&&null!=this.f[gfc_k].viewer&&this.f[gfc_k].viewer[gfc_F]()!=b.person[gfc_F]()&&(this.f[gfc_k][gfc_o].isFriend=c[gfc_l]()[gfc_x])};
gfc_7[gfc_].nu=function(a,b){var c=a.get("profile")[gfc_l]();this.f[gfc_k][gfc_o].person=c;this.f[gfc_k][gfc_o].person.externalProfileUrl=null;var d=c[gfc_I](gfc_e[gfc_y][gfc_r].URLS),e=[];if(d)for(var f=0;f<d[gfc_C];f++){var g=d[f];"profile"!=g[gfc_I](gfc_e.Url[gfc_r].TYPE)&&"externalProfile"!=g[gfc_I](gfc_e.Url[gfc_r].TYPE)&&e[gfc_w](g);"externalProfile"==g[gfc_I](gfc_e.Url[gfc_r].TYPE)&&(this.f[gfc_k][gfc_o].person.externalProfileUrl=g[gfc_I](gfc_e.Url[gfc_r].ADDRESS))}this.f[gfc_k][gfc_o].links=
new gfc_go(e,this.Ff,0);this.f[gfc_k].owner=a.get("owner")[gfc_l]();this.f[gfc_k].viewer=a.get("viewer")[gfc_l]();(d=this.f[gfc_k].viewer)&&b.person[gfc_F]()!=this.f[gfc_k].viewer[gfc_F]()&&(this.f[gfc_k][gfc_o].isAdmin=a.get("isAdmin")[gfc_l](),this.f[gfc_k][gfc_o].isAdmin&&(this.f[gfc_k][gfc_o].isAdmin=this.f[gfc_k][gfc_o].isAdmin[gfc_Nb]()),this.f[gfc_k][gfc_o].isBlocked=a.get("isBlocked")[gfc_l](),this.f[gfc_k][gfc_o].isBlocked&&(this.f[gfc_k][gfc_o].isBlocked=this.f[gfc_k][gfc_o].isBlocked[gfc_Nb]()));
c=c[gfc_I]("profileExtensions");c=this.Yb.xf(c,this.Yb.gj);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e[gfc_1c]||"LONG_TEXT"==e[gfc_1c])e[gfc_x]&&e[gfc_x][gfc_Ac]&&(g.body=[],g[gfc_D][gfc_w](e[gfc_x][gfc_Ac]),h=!0);else if(e[gfc_x]&&e[gfc_x].choice&&0<e[gfc_x].choice[gfc_C]){g.body=[];for(h=0;h<e[gfc_x].choice[gfc_C];++h)g[gfc_D][gfc_w](e[gfc_x].choice[h][gfc_mc]);h=!0}h&&d[gfc_w](g)}this.f[gfc_k][gfc_o].profileExtensions=d;this.vb||(this.vb=a.get("siteSettings")[gfc_l]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_l]().canSendMessage,this.f[gfc_k][gfc_o].canSendMessage=f);this.un(a)};gfc_7[gfc_].Rj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].tx=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_K(function(a,b,c){a[gfc_w](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].Dw=function(){this.pa();this.L("members-page")};
gfc_7[gfc_].Hw=function(){this.pa();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].Yw=function(){this.pj()};gfc_7[gfc_].mt=function(a){this.render(["member-page"],"members-page",{start:this.va+a.getOffset()})};gfc_7[gfc_].Vt=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.va})};gfc_7[gfc_].it=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.va+a.getOffset()})};
gfc_7[gfc_].Tt=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.va})};gfc_7[gfc_].Gw=function(){this.pa();this.L("viewer-friends-page")};gfc_7[gfc_].tt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.va+a.getOffset()})};gfc_7[gfc_].au=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.va})};gfc_7[gfc_].Ew=function(){this.pa();this.L("profile-friends-page")};
gfc_7[gfc_].rt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.va+a.getOffset(),person:this.f[gfc_k][gfc_o].person})};gfc_7[gfc_].Zt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.va,person:this.f[gfc_k][gfc_o].person})};gfc_7[gfc_].Cw=function(){this.pa();this.L("links")};gfc_7[gfc_].lt=function(a){var b=this.Ff+a.getOffset();this.f[gfc_k][gfc_o].links=new gfc_go(a.all(),this.Ff,b);this.L("links")};
gfc_7[gfc_].Ut=function(a){var b=a.getOffset()-this.Ff;this.f[gfc_k][gfc_o].links=new gfc_go(a.all(),this.Ff,b);this.L("links")};gfc_7[gfc_].Fw=function(){this.pa();this.L("sites")};gfc_7[gfc_].st=function(a){this.render(["sitesData"],"sites",{start:this.Tn+a.getOffset()})};gfc_7[gfc_].$t=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.Tn})};gfc_7[gfc_].Aw=function(){this.pa();this.L("activities")};
gfc_7[gfc_].ht=function(a){this.render(["activityData"],"activities",{start:this.Ka+a.getOffset()})};gfc_7[gfc_].St=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ka})};gfc_7[gfc_].of=function(a){this.render(["deleteActivity"],this.f[gfc_dd],{activity:a})};gfc_7[gfc_].cv=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ve(b.person[gfc_F](),["BLOCKED"],[]),"block");this.ld();c[gfc_n](a)};
gfc_7[gfc_].eu=function(a){if(a=!a.get("block")[gfc_Gc]())this.f[gfc_k][gfc_o].isBlocked=!0};gfc_7[gfc_].Av=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ve(b.person[gfc_F](),[],["BLOCKED"]),"unblock");this.ld();c[gfc_n](a)};gfc_7[gfc_].tu=function(a){if(a=!a.get("unblock")[gfc_Gc]())this.f[gfc_k][gfc_o].isBlocked=!1};
gfc_7[gfc_].Vf=function(a,b){var c=b.activity,d=c[gfc_I](gfc_e[gfc_$b][gfc_r].ID),c=gfc_e[gfc_rc]({userId:c[gfc_I](gfc_e[gfc_$b][gfc_r][gfc__b])}),e=gfc_e[gfc_H]();e.add(gfc_fe(d),"delete");e.add(e[gfc_9c](c,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].qc=function(a){var b=gfc_Fn,c=function(a){return a=a[gfc_j](/<a/g,"<a target='_top'")},d=null,e=this.f[gfc_k].viewer;null!=e&&a[gfc_I](gfc_e[gfc_$b][gfc_r][gfc__b])==this.f[gfc_k].viewer[gfc_F]()&&(d=gfc_K(this.of,this,a));(e=a[gfc_I](gfc_e[gfc_$b][gfc_r].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_b.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ga(a[gfc_I](gfc_e[gfc_$b][gfc_r].POSTED_TIME))),link:a[gfc_I](gfc_e[gfc_$b][gfc_r].STREAM_URL,{escapeType:"none"}),siteTitle:a[gfc_I](gfc_e[gfc_$b][gfc_r].STREAM_TITLE,
{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_e[gfc_$b][gfc_r].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_e[gfc_$b][gfc_r].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].px=function(a){var b=gfc_a[gfc_ec].unescapeString,c=gfc_eo;return{icon:c(a[gfc_I](gfc_e[gfc_y][gfc_r][gfc_Pc])),link:a[gfc_I](gfc_e[gfc_y][gfc_r][gfc_Pc]),title:b(a[gfc_0b]())}};
gfc_7[gfc_].ox=function(a){var b=gfc_a[gfc_ec].unescapeString,c=gfc_eo,d=a[gfc_I](gfc_e.Url[gfc_r].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_e.Url[gfc_r].LINK_TEXT))||d}};gfc_7[gfc_].qv=function(a,b){var c=gfc_e[gfc_H](),d=b.person[gfc_F](),e=gfc_e[gfc_E][gfc_Sc],f=this.qm(d),g={};g[gfc_e[gfc_E].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_5c];c.add(c[gfc_8b](f,g),"friends");f={};f[e.FIRST]=this.Py;f[e.MAX]=this.Oy;c.add(gfc_we(gfc_e[gfc_rc]({userId:d}),f),"profileSites");c[gfc_n](a)};
gfc_7[gfc_].bs=function(a){a={user:a[gfc_F](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Pg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Pg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].wv=function(a,b){var c=b[gfc_o],d=gfc_e[gfc_H]();d.add(gfc_ge(c[gfc_F](),b.message),"friendRequest");this.ld();d[gfc_n](a)};gfc_7[gfc_].ru=function(a){a.get("friendRequest")[gfc_Gc]()||(this.f[gfc_k][gfc_o].isInvited=!0)};
gfc_7[gfc_].gv=function(a,b){var c=gfc_co.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_co.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_a[gfc_bc].stringify(d)+"}"}));c.add("friendRequests",gfc_co.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.ld();c.execute(a)};gfc_7[gfc_].fr=function(){this.pa();this.L("invite-friend")};gfc_7[gfc_].Xv=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_e[gfc_y][gfc_r].ID),this.Yv(a))};
gfc_7[gfc_].Yv=function(a){this.isMessagingEnabled&&(a="/friendconnect/messaging/compose?recipientId="+a,gfc_on(a,"570","395"))};gfc_1[gfc_].Ao=function(){gfc_on("/friendconnect/messaging/accept","570","375");return!1};gfc_7[gfc_].er=function(){this.pa();this.L("block-member")};gfc_7[gfc_].gr=function(){this.qo(this.f[gfc_k].viewer)};gfc_7[gfc_].Wv=function(a){this.Lf();a={profile:a};var b=gfc_O("inviteMessage");b&&(a.message=gfc_qh(b));this.render(["sendFriendRequest"],"profile",a)};
gfc_7[gfc_].Uo=function(a){this.Lf();this.Rj(a)};gfc_7[gfc_].Nm=function(a,b,c){c=c||!1;this.f[gfc_k].friendRequests=gfc_re(a.friendRequests,gfc_ie);0<this.f[gfc_k].friendRequests[gfc_Nb]()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_$m("friend")};gfc_7[gfc_].pu=function(a){this.f[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]();this.f[gfc_k][gfc_o].friends=a.get("friends")[gfc_l]()};gfc_7[gfc_].Sq=function(){return this.Pw};
gfc_7[gfc_].ga=function(){this.ny.rebuild();this.Ho();gfc_a[gfc_0c].adjustHeight()};gfc_7[gfc_].It=function(a){return a=gfc_P("span",{"class":"fc-cap-link-big"},gfc_P("a",{"class":"fc-cap-link-big"},this.g.MSG_OPTIONS),a.Vg())};
gfc_7[gfc_].Ht=function(){var a=[];a[a[gfc_C]]=gfc_P("div",{"class":"goog-menuitem menuaction-settings"},this.g.MSG_SITE_SETTINGS);this.isSocialShareEnabled&&(a[a[gfc_C]]=gfc_P("div",{"class":"goog-menuitem menuaction-share"},this.g.MSG_MEMBERS_SHARE));this.f[gfc_k].isViewerAdmin&&!this.Ub()&&(a[a[gfc_C]]=gfc_P("div",{"class":"goog-menuitem menuaction-manage"},this.g.MSG_MANAGE));a[a[gfc_C]]=gfc_P("div",{"class":"goog-menuitem menuaction-signout"},this.vb.signOutPrompt||this.g.MSG_SIGN_OUT);a[a[gfc_C]]=
gfc_P("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_C]]=gfc_P("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_P("span",{"class":"fc-small-menu-link"},this.g.MSG_ABOUT_FC));return a};
gfc_7[gfc_].Jt=function(a){a[gfc_Xb]();a=a[gfc_fd].i()[gfc_2c];a[gfc_gb]("menuaction-settings")?this.Nb():a[gfc_gb]("menuaction-share")?this.share():a[gfc_gb]("menuaction-signout")?this.signout():a[gfc_gb]("menuaction-manage")?this.kr():a[gfc_gb]("menuaction-aboutfc")&&(a=gfc_b[gfc_xc](gfc_gn()+"/friendconnect/home/overview"),a[gfc_mb]())};gfc_7[gfc_].kr=function(){var a={},b=gfc_a[gfc_s][gfc_8a]()[gfc_oc];gfc_$m("lightbox");gfc_a[gfc_s].requestNavigateTo(b,a);return!1};
var gfc_fo=function(a){for(var b={},c=0;c<a[gfc_C];++c)b[a[c]]=a[c];return b}("HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "));
gfc_7[gfc_].D=function(){var a=gfc_fo,b=[],c=0;this.h(a.HEIGHT);this.ji()&&(b[c++]=this.m(".fc-thumbnail img {height:%spx;width:%spx}",this.h(a.FACE_SIZE)));b[c++]=this.m(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.qn);b[c++]=this.m(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.h(a.BORDER_COLOR));this.vf()&&(this.vl("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.mi()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Ub()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.mi()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.m(".fc-topcap-color {background-color: %s;}\n",this.h(a.ENDCAP_BG_COLOR));this.Ml()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.m(".fc-botcap-short {background-color: %s;}\n",this.h(a.ENDCAP_BG_COLOR));b[c++]=this.m(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.h(a.ENDCAP_BG_COLOR));b[c++]=this.m(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.h(a.ENDCAP_BG_COLOR));b[c++]=this.m(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.h(a.ENDCAP_TEXT_COLOR));
b[c++]=this.m(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.h(a.ENDCAP_LINK_COLOR));b[c++]=this.m(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.h(a.CONTENT_BG_COLOR));b[c++]=this.m(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.h(a.CONTENT_LINK_COLOR));b[c++]=this.m(".fc-members,.fc-members-canvas {color:%s;}\n",this.h(a.CONTENT_TEXT_COLOR));b[c++]=this.m(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.h(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.m(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.h(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.m(".fc-sectitle {color: %s;}\n",
this.h(a.CONTENT_HEADLINE_COLOR));return gfc_7.l.D[gfc_G](this)+b[gfc_J]("\n")};gfc_L("goog.peoplesense.gadget.Members",gfc_7);gfc_L("goog.peoplesense.gadget.Members.start",gfc_7[gfc_u]);var gfc_go=function(a,b,c){gfc_e.Collection[gfc_G](this,a[gfc_Cc](c,c+b),c,a[gfc_C]);this.Ox=a;this.na=b};gfc_go.inherits(gfc_e.Collection);gfc_go[gfc_].all=function(){return this.Ox};gfc_go[gfc_].Cb=function(){return this.na};gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_go[gfc_].all);
gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_go[gfc_].Cb);
